In [1]:
import os
import pandas as pd

# Get the current working directory 
current_directory = os.getcwd() 

# Print the current working directory 
print(current_directory)

# Define the directory containing the files 
path = current_directory+"\\"
print(path)

filename = path + 'Daily_Data_All.csv'

results_df = pd.read_csv(filename) #read csv data into a dataframe

print(results_df)

C:\Users\User
C:\Users\User\
              time  longitude  latitude  elevation  temperatures          slp  \
0       2006-01-01    -91.756    33.636       85.0     16.229167  1008.741667
1       2006-01-02    -91.756    33.636       85.0     21.579166  1006.045833
2       2006-01-03    -91.756    33.636       85.0     13.849999  1016.579166
3       2006-01-04    -91.756    33.636       85.0     17.183333  1015.295834
4       2006-01-05    -91.756    33.636       85.0     12.820833  1019.033334
...            ...        ...       ...        ...           ...          ...
732349  2024-11-26    -97.091    36.118      271.3      3.604167  1024.958333
732350  2024-11-27    -97.091    36.118      271.3      9.420835  1008.625000
732351  2024-11-28    -97.091    36.118      271.3      4.395833  1022.358333
732352  2024-11-29    -97.091    36.118      271.3      2.020833  1028.241666
732353  2024-11-30    -97.091    36.118      271.3      6.562500  1021.904167

        vapor_pressure  wet_bulb_temperature  specific_humidity  file_id  ...  \
0            13.413650             12.647472           8.414445     6501  ...
1            15.519149             16.296734           9.766870     6501  ...
2             7.984096              8.360605           4.953657     6501  ...
3             8.457418             10.352193           5.253664     6501  ...
4             6.542248              6.840904           4.047499     6501  ...
...                ...                   ...                ...      ...  ...
732349        4.307189             -0.160447           2.713575     9858  ...
732350        7.403495              5.706456           4.744895     9858  ...
732351        5.131844              1.013759           3.243887     9858  ...
732352        4.264967             -1.153450           2.678646     9858  ...
732353        4.972497              2.220070           3.141820     9858  ...

        MXSPD   GUST   MAX  MAX_ATTRIBUTES   MIN MIN_ATTRIBUTES  PRCP  \
0        11.8   18.8  73.9                  36.0                 0.00
1        15.9   26.8  73.9                  51.1                 0.00
2         7.0  999.9  73.9                  39.9                 0.00
3         8.9   16.9  75.9               *  55.0              *  0.00
4        15.0   22.7  77.0                  39.9                 0.00
...       ...    ...   ...             ...   ...            ...   ...
732349  999.9  999.9  56.5                  21.7                 0.00
732350  999.9  999.9  56.1                  36.7                 0.00
732351  999.9  999.9  51.1                  28.8                 0.00
732352  999.9  999.9  54.0                  19.9                 0.00
732353  999.9  999.9  54.5                  30.2                 0.01

        PRCP_ATTRIBUTES   SNDP  FRSHTT
0                     G  999.9     0.0
1                     G  999.9     0.0
2                     G  999.9     0.0
3                     G  999.9     0.0
4                     G  999.9     0.0
...                 ...    ...     ...
732349                G  999.9     0.0
732350                G  999.9     0.0
732351                G  999.9     0.0
732352                G  999.9     0.0
732353                G  999.9     0.0

[732354 rows x 41 columns]

In [3]:
print(results_df.columns)

Index(['time', 'longitude', 'latitude', 'elevation', 'temperatures', 'slp',
       'vapor_pressure', 'wet_bulb_temperature', 'specific_humidity',
       'file_id', 'region', 'water', 'GHI', 'wind_speed', 'WMO_ID',
       'NOAA_file_csv', 'DATE', 'STATION', 'NAME', 'TEMP', 'TEMP_ATTRIBUTES',
       'DEWP', 'DEWP_ATTRIBUTES', 'SLP', 'SLP_ATTRIBUTES', 'STP',
       'STP_ATTRIBUTES', 'VISIB', 'VISIB_ATTRIBUTES', 'WDSP',
       'WDSP_ATTRIBUTES', 'MXSPD', 'GUST', 'MAX', 'MAX_ATTRIBUTES', 'MIN',
       'MIN_ATTRIBUTES', 'PRCP', 'PRCP_ATTRIBUTES', 'SNDP', 'FRSHTT'],
      dtype='object')

In [12]:
import pandas as pd

# Function to check if a value is non-numeric
def is_non_numeric(value):
    return not pd.api.types.is_numeric_dtype(type(value))

# Count non-numeric values in the average (mean) wind speed column
non_numeric_count = results_df['WDSP'].apply(is_non_numeric).sum()

print(f"Number of non-numeric values: {non_numeric_count}")

# Count non-numeric values in the snow depth column
non_numeric_count = results_df['SNDP'].apply(is_non_numeric).sum()

print(f"Number of non-numeric values: {non_numeric_count}")

# Count non-numeric values in the precipitation column
non_numeric_count = results_df['PRCP'].apply(is_non_numeric).sum()

print(f"Number of non-numeric values: {non_numeric_count}")

#There are no non-numeric values

Number of non-numeric values: 0
Number of non-numeric values: 0
Number of non-numeric values: 0

In [5]:
print(results_df['WDSP'])

0           6.2
1          12.3
2           3.7
3           6.2
4           6.2
          ...
732349    999.9
732350    999.9
732351    999.9
732352    999.9
732353    999.9
Name: WDSP, Length: 732354, dtype: float64

In [11]:
#Find how many missing values are in each column
count = results_df['WDSP'].value_counts().get(999.9, 0)
print(count)
count = results_df['SNDP'].value_counts().get(999.9, 0)
print(count)
count = results_df['slp'].value_counts().get(999.9, 0)
print(count)
count = results_df['SLP'].value_counts().get(999.9, 0)
print(count)
count = results_df['MXSPD'].value_counts().get(999.9, 0)
print(count)
count = results_df['PRCP'].value_counts().get(99.99, 0)
print(count)
count = results_df['GUST'].value_counts().get(999.9, 0)
print(count)
count = results_df['DEWP'].value_counts().get(999.9, 0)
print(count)
count = results_df['STP'].value_counts().get(999.9, 0)
print(count)
count = results_df['MIN'].value_counts().get(9999.9, 0)
print(count)
count = results_df['MAX'].value_counts().get(9999.9, 0)
print(count)
count = results_df['TEMP'].value_counts().get(9999.9, 0)
print(count)

6901
725346
0
181
7044
514
290767
0
17581
50
593
0

In [13]:
results2_df = results_df.drop(['SLP', 'MXSPD', 'GUST', 'DEWP', 'STP', 'MIN', 'MAX', 'TEMP', 'FRSHTT', 'VISIB', 'MIN_ATTRIBUTES', 'MAX_ATTRIBUTES', 'TEMP_ATTRIBUTES', 'SLP_ATTRIBUTES', 'VISIB_ATTRIBUTES', 'STP_ATTRIBUTES', 'PRCP_ATTRIBUTES', 'DEWP_ATTRIBUTES', 'WDSP_ATTRIBUTES'], axis=1)

In [14]:
print(results2_df)

              time  longitude  latitude  elevation  temperatures          slp  \
0       2006-01-01    -91.756    33.636       85.0     16.229167  1008.741667
1       2006-01-02    -91.756    33.636       85.0     21.579166  1006.045833
2       2006-01-03    -91.756    33.636       85.0     13.849999  1016.579166
3       2006-01-04    -91.756    33.636       85.0     17.183333  1015.295834
4       2006-01-05    -91.756    33.636       85.0     12.820833  1019.033334
...            ...        ...       ...        ...           ...          ...
732349  2024-11-26    -97.091    36.118      271.3      3.604167  1024.958333
732350  2024-11-27    -97.091    36.118      271.3      9.420835  1008.625000
732351  2024-11-28    -97.091    36.118      271.3      4.395833  1022.358333
732352  2024-11-29    -97.091    36.118      271.3      2.020833  1028.241666
732353  2024-11-30    -97.091    36.118      271.3      6.562500  1021.904167

        vapor_pressure  wet_bulb_temperature  specific_humidity  file_id  ...  \
0            13.413650             12.647472           8.414445     6501  ...
1            15.519149             16.296734           9.766870     6501  ...
2             7.984096              8.360605           4.953657     6501  ...
3             8.457418             10.352193           5.253664     6501  ...
4             6.542248              6.840904           4.047499     6501  ...
...                ...                   ...                ...      ...  ...
732349        4.307189             -0.160447           2.713575     9858  ...
732350        7.403495              5.706456           4.744895     9858  ...
732351        5.131844              1.013759           3.243887     9858  ...
732352        4.264967             -1.153450           2.678646     9858  ...
732353        4.972497              2.220070           3.141820     9858  ...

               GHI  wind_speed        WMO_ID    NOAA_file_csv        DATE  \
0        48.833333    6.750000  720175-53919  72017553919.csv  2006-01-01
1       144.875000    9.750000  720175-53919  72017553919.csv  2006-01-02
2       147.666667    3.666667  720175-53919  72017553919.csv  2006-01-03
3       116.416667    4.708333  720175-53919  72017553919.csv  2006-01-04
4       142.666667    5.708333  720175-53919  72017553919.csv  2006-01-05
...            ...         ...           ...              ...         ...
732349         NaN         NaN  999999-53927  99999953927.csv  2024-11-26
732350         NaN         NaN  999999-53927  99999953927.csv  2024-11-27
732351         NaN         NaN  999999-53927  99999953927.csv  2024-11-28
732352         NaN         NaN  999999-53927  99999953927.csv  2024-11-29
732353         NaN         NaN  999999-53927  99999953927.csv  2024-11-30

             STATION                                 NAME   WDSP  PRCP   SNDP
0       7.201755e+10  MONTICELLO MUNICIPAL AIRPORT, AR US    6.2  0.00  999.9
1       7.201755e+10  MONTICELLO MUNICIPAL AIRPORT, AR US   12.3  0.00  999.9
2       7.201755e+10  MONTICELLO MUNICIPAL AIRPORT, AR US    3.7  0.00  999.9
3       7.201755e+10  MONTICELLO MUNICIPAL AIRPORT, AR US    6.2  0.00  999.9
4       7.201755e+10  MONTICELLO MUNICIPAL AIRPORT, AR US    6.2  0.00  999.9
...              ...                                  ...    ...   ...    ...
732349  9.999995e+10              STILLWATER 5 WNW, OK US  999.9  0.00  999.9
732350  9.999995e+10              STILLWATER 5 WNW, OK US  999.9  0.00  999.9
732351  9.999995e+10              STILLWATER 5 WNW, OK US  999.9  0.00  999.9
732352  9.999995e+10              STILLWATER 5 WNW, OK US  999.9  0.00  999.9
732353  9.999995e+10              STILLWATER 5 WNW, OK US  999.9  0.01  999.9

[732354 rows x 22 columns]

In [16]:
results2_df = results2_df.drop(['NAME', 'WMO_ID', 'wind_speed', 'NOAA_file_csv'], axis=1) #wind_speed is from NSRDB data. We are using NOAA variable WDSP instead.

In [17]:
print(results2_df)

              time  longitude  latitude  elevation  temperatures          slp  \
0       2006-01-01    -91.756    33.636       85.0     16.229167  1008.741667
1       2006-01-02    -91.756    33.636       85.0     21.579166  1006.045833
2       2006-01-03    -91.756    33.636       85.0     13.849999  1016.579166
3       2006-01-04    -91.756    33.636       85.0     17.183333  1015.295834
4       2006-01-05    -91.756    33.636       85.0     12.820833  1019.033334
...            ...        ...       ...        ...           ...          ...
732349  2024-11-26    -97.091    36.118      271.3      3.604167  1024.958333
732350  2024-11-27    -97.091    36.118      271.3      9.420835  1008.625000
732351  2024-11-28    -97.091    36.118      271.3      4.395833  1022.358333
732352  2024-11-29    -97.091    36.118      271.3      2.020833  1028.241666
732353  2024-11-30    -97.091    36.118      271.3      6.562500  1021.904167

        vapor_pressure  wet_bulb_temperature  specific_humidity  file_id  \
0            13.413650             12.647472           8.414445     6501
1            15.519149             16.296734           9.766870     6501
2             7.984096              8.360605           4.953657     6501
3             8.457418             10.352193           5.253664     6501
4             6.542248              6.840904           4.047499     6501
...                ...                   ...                ...      ...
732349        4.307189             -0.160447           2.713575     9858
732350        7.403495              5.706456           4.744895     9858
732351        5.131844              1.013759           3.243887     9858
732352        4.264967             -1.153450           2.678646     9858
732353        4.972497              2.220070           3.141820     9858

        region  water         GHI        DATE       STATION   WDSP  PRCP  \
0            4      1   48.833333  2006-01-01  7.201755e+10    6.2  0.00
1            4      1  144.875000  2006-01-02  7.201755e+10   12.3  0.00
2            4      1  147.666667  2006-01-03  7.201755e+10    3.7  0.00
3            4      1  116.416667  2006-01-04  7.201755e+10    6.2  0.00
4            4      1  142.666667  2006-01-05  7.201755e+10    6.2  0.00
...        ...    ...         ...         ...           ...    ...   ...
732349       4      1         NaN  2024-11-26  9.999995e+10  999.9  0.00
732350       4      1         NaN  2024-11-27  9.999995e+10  999.9  0.00
732351       4      1         NaN  2024-11-28  9.999995e+10  999.9  0.00
732352       4      1         NaN  2024-11-29  9.999995e+10  999.9  0.00
732353       4      1         NaN  2024-11-30  9.999995e+10  999.9  0.01

         SNDP
0       999.9
1       999.9
2       999.9
3       999.9
4       999.9
...       ...
732349  999.9
732350  999.9
732351  999.9
732352  999.9
732353  999.9

[732354 rows x 18 columns]

In [31]:
import pandas as pd
import numpy as np

# Replace numeric 99.99 values with NaN in PRCP 
results2_df['PRCP'] = results2_df['PRCP'].replace({99.99: np.nan})

# Replace numeric 999.9 values with NaN in WDSP 
results2_df['WDSP'] = results2_df['WDSP'].replace({999.9: np.nan})

# Replace numeric 999.9 values with zero in SNDP 
results2_df['SNDP'] = results2_df['SNDP'].replace({999.9: 0})

print(results2_df)

              time  longitude  latitude  elevation  temperatures          slp  \
0       2006-01-01    -91.756    33.636       85.0     16.229167  1008.741667
1       2006-01-02    -91.756    33.636       85.0     21.579166  1006.045833
2       2006-01-03    -91.756    33.636       85.0     13.849999  1016.579166
3       2006-01-04    -91.756    33.636       85.0     17.183333  1015.295834
4       2006-01-05    -91.756    33.636       85.0     12.820833  1019.033334
...            ...        ...       ...        ...           ...          ...
732349  2024-11-26    -97.091    36.118      271.3      3.604167  1024.958333
732350  2024-11-27    -97.091    36.118      271.3      9.420835  1008.625000
732351  2024-11-28    -97.091    36.118      271.3      4.395833  1022.358333
732352  2024-11-29    -97.091    36.118      271.3      2.020833  1028.241666
732353  2024-11-30    -97.091    36.118      271.3      6.562500  1021.904167

        vapor_pressure  wet_bulb_temperature  specific_humidity  file_id  \
0            13.413650             12.647472           8.414445     6501
1            15.519149             16.296734           9.766870     6501
2             7.984096              8.360605           4.953657     6501
3             8.457418             10.352193           5.253664     6501
4             6.542248              6.840904           4.047499     6501
...                ...                   ...                ...      ...
732349        4.307189             -0.160447           2.713575     9858
732350        7.403495              5.706456           4.744895     9858
732351        5.131844              1.013759           3.243887     9858
732352        4.264967             -1.153450           2.678646     9858
732353        4.972497              2.220070           3.141820     9858

        region  water         GHI        DATE       STATION  WDSP  PRCP  SNDP  \
0            4      1   48.833333  2006-01-01  7.201755e+10   6.2  0.00   0.0
1            4      1  144.875000  2006-01-02  7.201755e+10  12.3  0.00   0.0
2            4      1  147.666667  2006-01-03  7.201755e+10   3.7  0.00   0.0
3            4      1  116.416667  2006-01-04  7.201755e+10   6.2  0.00   0.0
4            4      1  142.666667  2006-01-05  7.201755e+10   6.2  0.00   0.0
...        ...    ...         ...         ...           ...   ...   ...   ...
732349       4      1         NaN  2024-11-26  9.999995e+10   NaN  0.00   0.0
732350       4      1         NaN  2024-11-27  9.999995e+10   NaN  0.00   0.0
732351       4      1         NaN  2024-11-28  9.999995e+10   NaN  0.00   0.0
732352       4      1         NaN  2024-11-29  9.999995e+10   NaN  0.00   0.0
732353       4      1         NaN  2024-11-30  9.999995e+10   NaN  0.01   0.0

             date
0      2006-01-01
1      2006-01-02
2      2006-01-03
3      2006-01-04
4      2006-01-05
...           ...
732349 2024-11-26
732350 2024-11-27
732351 2024-11-28
732352 2024-11-29
732353 2024-11-30

[732354 rows x 19 columns]

In [32]:
import pandas as pd
from datetime import datetime 

# Function to check if a value is non-numeric
def is_non_numeric(value):
    return not pd.api.types.is_numeric_dtype(type(value))

# Count non-numeric values in the GHI column
non_numeric_count = results2_df['GHI'].apply(is_non_numeric).sum()

print(f"Number of non-numeric values: {non_numeric_count}")

# Convert the 'time' column from string to datetime
results2_df['date'] = pd.to_datetime(results2_df['time'])

results2_df[results2_df['date'] < datetime.strptime("2024-12-1", "%Y-%m-%d")].isna().sum()

Number of non-numeric values: 0

time                         0
longitude                   65
latitude                    65
elevation                   65
temperatures                65
slp                         65
vapor_pressure              65
wet_bulb_temperature        65
specific_humidity           65
file_id                      0
region                       0
water                        0
GHI                     151580
DATE                         0
STATION                   1644
WDSP                      8545
PRCP                      2158
SNDP                      1644
date                         0
dtype: int64

In [78]:
#From binning data from hourly to daily, there are 65 days for which hourly data was missing for all 24 hours of the day. 
#These rows are missing latitude, longitude, and elevation which we will fill in manually in Python using their file_id 
#so that binning to monthly will not skew location data
# Find rows with NaN values in column 'latitude'
nan_rows = results2_df.loc[results2_df['latitude'].isnull()]

index = nan_rows.index
print(index)

filename = path + 'filenames_chosen.csv'

locations_df = pd.read_csv(filename) #read location data into a dataframe

print(locations_df)

results3_df = results2_df

#”VLOOKUP” operation to get latitude, longitude, elevation, and region for missing data
results3_df = pd.merge(results3_df, locations_df, left_on='file_id', right_on = 'file_no', how='left')

print(results3_df)

Index([ 22818,  59172,  97552,  97553, 156426, 181727, 200298, 200299, 203910,
       207207, 207208, 207210, 207211, 219111, 219112, 219113, 219114, 229121,
       229122, 229127, 231840, 248660, 248661, 256757, 270941, 270942, 270943,
       277449, 277450, 277451, 277452, 277453, 306491, 306493, 306494, 366512,
       366513, 410844, 412962, 413679, 416551, 428218, 428219, 430853, 448595,
       455550, 455551, 455552, 455553, 483923, 483924, 483925, 483926, 484108,
       492283, 498436, 498437, 535164, 568890, 568891, 617995, 617996, 617997,
       617998, 619477],
      dtype='int64')
     file_no  latitude  longitude  elevation  region  start_date  end_date  \
0       6501    33.636    -91.756       85.0       4    20050101  20241130
1       6541    38.958    -94.371      304.8       4    20040525  20241130
2       6640    28.474    -82.454       19.7       6    19990101  20241130
3       6668    35.140    -90.236       63.7       4    20040319  20241130
4       6678    30.393    -86.467        5.4       6    19970101  20241130
..       ...       ...        ...        ...     ...         ...       ...
103     8184    36.985   -120.111       76.6       2    19990101  20241130
104     8186    33.038   -116.916      422.0       2    19990101  20241130
105     8247    30.337    -81.513       11.9       6    20050101  20241130
106     8248    26.079    -80.162        1.0       6    20050101  20241130
107     9858    36.118    -97.091      271.3       4    20020312  20241130

     missing                                           filename
0        266  hadisd.3.4.1.202411p_19310101-20241201_720175-...
1        571  hadisd.3.4.1.202411p_19310101-20241201_720306-...
2        521  hadisd.3.4.1.202411p_19310101-20241201_722014-...
3        394  hadisd.3.4.1.202411p_19310101-20241201_722054-...
4        482  hadisd.3.4.1.202411p_19310101-20241201_722069-...
..       ...                                                ...
103      455  hadisd.3.4.1.202411p_19310101-20241201_745046-...
104      322  hadisd.3.4.1.202411p_19310101-20241201_745056-...
105      602  hadisd.3.4.1.202411p_19310101-20241201_747820-...
106      551  hadisd.3.4.1.202411p_19310101-20241201_747830-...
107      153  hadisd.3.4.1.202411p_19310101-20241201_999999-...

[108 rows x 9 columns]
              time  longitude_x  latitude_x  elevation_x  temperatures  \
0       2006-01-01      -91.756      33.636         85.0     16.229167
1       2006-01-02      -91.756      33.636         85.0     21.579166
2       2006-01-03      -91.756      33.636         85.0     13.849999
3       2006-01-04      -91.756      33.636         85.0     17.183333
4       2006-01-05      -91.756      33.636         85.0     12.820833
...            ...          ...         ...          ...           ...
732349  2024-11-26      -97.091      36.118        271.3      3.604167
732350  2024-11-27      -97.091      36.118        271.3      9.420835
732351  2024-11-28      -97.091      36.118        271.3      4.395833
732352  2024-11-29      -97.091      36.118        271.3      2.020833
732353  2024-11-30      -97.091      36.118        271.3      6.562500

                slp  vapor_pressure  wet_bulb_temperature  specific_humidity  \
0       1008.741667       13.413650             12.647472           8.414445
1       1006.045833       15.519149             16.296734           9.766870
2       1016.579166        7.984096              8.360605           4.953657
3       1015.295834        8.457418             10.352193           5.253664
4       1019.033334        6.542248              6.840904           4.047499
...             ...             ...                   ...                ...
732349  1024.958333        4.307189             -0.160447           2.713575
732350  1008.625000        7.403495              5.706456           4.744895
732351  1022.358333        5.131844              1.013759           3.243887
732352  1028.241666        4.264967             -1.153450           2.678646
732353  1021.904167        4.972497              2.220070           3.141820

        file_id  ...       date  file_no  latitude_y longitude_y  elevation_y  \
0          6501  ... 2006-01-01     6501      33.636     -91.756         85.0
1          6501  ... 2006-01-02     6501      33.636     -91.756         85.0
2          6501  ... 2006-01-03     6501      33.636     -91.756         85.0
3          6501  ... 2006-01-04     6501      33.636     -91.756         85.0
4          6501  ... 2006-01-05     6501      33.636     -91.756         85.0
...         ...  ...        ...      ...         ...         ...          ...
732349     9858  ... 2024-11-26     9858      36.118     -97.091        271.3
732350     9858  ... 2024-11-27     9858      36.118     -97.091        271.3
732351     9858  ... 2024-11-28     9858      36.118     -97.091        271.3
732352     9858  ... 2024-11-29     9858      36.118     -97.091        271.3
732353     9858  ... 2024-11-30     9858      36.118     -97.091        271.3

        region_y  start_date  end_date missing  \
0              4    20050101  20241130     266
1              4    20050101  20241130     266
2              4    20050101  20241130     266
3              4    20050101  20241130     266
4              4    20050101  20241130     266
...          ...         ...       ...     ...
732349         4    20020312  20241130     153
732350         4    20020312  20241130     153
732351         4    20020312  20241130     153
732352         4    20020312  20241130     153
732353         4    20020312  20241130     153

                                                 filename
0       hadisd.3.4.1.202411p_19310101-20241201_720175-...
1       hadisd.3.4.1.202411p_19310101-20241201_720175-...
2       hadisd.3.4.1.202411p_19310101-20241201_720175-...
3       hadisd.3.4.1.202411p_19310101-20241201_720175-...
4       hadisd.3.4.1.202411p_19310101-20241201_720175-...
...                                                   ...
732349  hadisd.3.4.1.202411p_19310101-20241201_999999-...
732350  hadisd.3.4.1.202411p_19310101-20241201_999999-...
732351  hadisd.3.4.1.202411p_19310101-20241201_999999-...
732352  hadisd.3.4.1.202411p_19310101-20241201_999999-...
732353  hadisd.3.4.1.202411p_19310101-20241201_999999-...

[732354 rows x 28 columns]

In [48]:
#Confirm location of NaN values by index
print(results3_df.loc[22817:22819])

             time  longitude_x  latitude_x  elevation_x  temperatures  \
22817  2011-09-22      -90.236       35.14         63.7     20.929166
22818  2011-09-23          NaN         NaN          NaN           NaN
22819  2011-09-24      -90.236       35.14         63.7     24.271430

               slp  vapor_pressure  wet_bulb_temperature  specific_humidity  \
22817  1017.708333       17.263373             17.129928          10.704979
22818          NaN             NaN                   NaN                NaN
22819  1011.942857       13.722292             16.602925           8.545249

       file_id  ...       date  file_no  latitude_y longitude_y  elevation_y  \
22817     6668  ... 2011-09-22     6668       35.14     -90.236         63.7
22818     6668  ... 2011-09-23     6668       35.14     -90.236         63.7
22819     6668  ... 2011-09-24     6668       35.14     -90.236         63.7

       region_y  start_date  end_date missing  \
22817         4    20040319  20241130     394
22818         4    20040319  20241130     394
22819         4    20040319  20241130     394

                                                filename
22817  hadisd.3.4.1.202411p_19310101-20241201_722054-...
22818  hadisd.3.4.1.202411p_19310101-20241201_722054-...
22819  hadisd.3.4.1.202411p_19310101-20241201_722054-...

[3 rows x 28 columns]

In [49]:
#Clean data for location information
results3_df['latitude'] = results3_df['latitude_y']
results3_df['longitude'] = results3_df['longitude_y']
results3_df['elevation'] = results3_df['elevation_y']
results3_df = results3_df.drop(['latitude_x', 'longitude_x', 'elevation_x'], axis=1)
results3_df = results3_df.drop(['latitude_y', 'longitude_y', 'elevation_y'], axis=1)
print(results3_df.columns)

Index(['time', 'temperatures', 'slp', 'vapor_pressure', 'wet_bulb_temperature',
       'specific_humidity', 'file_id', 'region_x', 'water', 'GHI', 'DATE',
       'STATION', 'WDSP', 'PRCP', 'SNDP', 'date', 'file_no', 'region_y',
       'start_date', 'end_date', 'missing', 'filename', 'latitude',
       'longitude', 'elevation'],
      dtype='object')

In [50]:
results3_df['region'] = results3_df['region_y']
results3_df = results3_df.drop(['region_x', 'region_y', 'filename', 'file_no'], axis=1)
results3_df = results3_df.drop(['missing', 'start_date', 'end_date'], axis=1)
print(results3_df.columns)

Index(['time', 'temperatures', 'slp', 'vapor_pressure', 'wet_bulb_temperature',
       'specific_humidity', 'file_id', 'water', 'GHI', 'DATE', 'STATION',
       'WDSP', 'PRCP', 'SNDP', 'date', 'latitude', 'longitude', 'elevation',
       'region'],
      dtype='object')

In [55]:
from datetime import datetime 

#Check location data is now clean
results3_df[results3_df['date'] < datetime.strptime("2025-1-1", "%Y-%m-%d")].isna().sum()

time                         0
temperatures                65
slp                         65
vapor_pressure              65
wet_bulb_temperature        65
specific_humidity           65
file_id                      0
water                        0
GHI                     151580
DATE                         0
STATION                   1644
WDSP                      8545
PRCP                      2158
SNDP                      1644
date                         0
latitude                     0
longitude                    0
elevation                    0
region                       0
dtype: int64

In [57]:
from datetime import datetime 
import pandas as pd
import numpy as np

# Show GHI column has no NaN values before 2021
results3_df[results3_df['date'] < datetime.strptime("2021-1-1", "%Y-%m-%d")].isna().sum()

# Replace NaN values with numeric 999999.9 values in GHI for 1-1-2021 until the end of 2024 to bin data to monthly later 
results3_df['GHI'] = results3_df['GHI'].replace({np.nan: 999999.9})

In [58]:
results3_df[results3_df['date'] < datetime.strptime("2025-1-1", "%Y-%m-%d")].isna().sum()

time                       0
temperatures              65
slp                       65
vapor_pressure            65
wet_bulb_temperature      65
specific_humidity         65
file_id                    0
water                      0
GHI                        0
DATE                       0
STATION                 1644
WDSP                    8545
PRCP                    2158
SNDP                    1644
date                       0
latitude                   0
longitude                  0
elevation                  0
region                     0
dtype: int64

In [71]:
#Get WDC-SILSO data into a dataframe

path_SILSO = current_directory+"\\Data\\WDC-SILSO\\"
filename_SILSO = path_SILSO + 'SN_d_tot_V2.0.csv'

solar_activity_df = pd.read_csv(filename_SILSO, sep=';') #read solar activity data into a dataframe

# First three columns are year, month, and day. Fifth column is solar activity (number of sunspots per day)
solar_activity_df.columns = ['Year', 'Month', 'Day', 'Year_Fraction', 'solar_activity', 'error', 'Column7', 'Column8'] 

#Drop last three columns
solar_activity_df = solar_activity_df.iloc[:, :-3]

solar_activity_df['date'] = pd.to_datetime(solar_activity_df[['Year', 'Month', 'Day']])

solar_activity_df = solar_activity_df.drop(['Year_Fraction'], axis=1)

print(solar_activity_df)

combined_df = pd.merge(results3_df, solar_activity_df, on='date', how='left')

print(combined_df)

       Year  Month  Day  solar_activity       date
0      1818      1    2              -1 1818-01-02
1      1818      1    3              -1 1818-01-03
2      1818      1    4              -1 1818-01-04
3      1818      1    5              -1 1818-01-05
4      1818      1    6              -1 1818-01-06
...     ...    ...  ...             ...        ...
75569  2024     11   26             160 2024-11-26
75570  2024     11   27             205 2024-11-27
75571  2024     11   28             170 2024-11-28
75572  2024     11   29             161 2024-11-29
75573  2024     11   30             121 2024-11-30

[75574 rows x 5 columns]
              time  temperatures          slp  vapor_pressure  \
0       2006-01-01     16.229167  1008.741667       13.413650
1       2006-01-02     21.579166  1006.045833       15.519149
2       2006-01-03     13.849999  1016.579166        7.984096
3       2006-01-04     17.183333  1015.295834        8.457418
4       2006-01-05     12.820833  1019.033334        6.542248
...            ...           ...          ...             ...
732349  2024-11-26      3.604167  1024.958333        4.307189
732350  2024-11-27      9.420835  1008.625000        7.403495
732351  2024-11-28      4.395833  1022.358333        5.131844
732352  2024-11-29      2.020833  1028.241666        4.264967
732353  2024-11-30      6.562500  1021.904167        4.972497

        wet_bulb_temperature  specific_humidity  file_id  water  \
0                  12.647472           8.414445     6501      1
1                  16.296734           9.766870     6501      1
2                   8.360605           4.953657     6501      1
3                  10.352193           5.253664     6501      1
4                   6.840904           4.047499     6501      1
...                      ...                ...      ...    ...
732349             -0.160447           2.713575     9858      1
732350              5.706456           4.744895     9858      1
732351              1.013759           3.243887     9858      1
732352             -1.153450           2.678646     9858      1
732353              2.220070           3.141820     9858      1

                  GHI        DATE  ...  SNDP       date  latitude  longitude  \
0           48.833333  2006-01-01  ...   0.0 2006-01-01    33.636    -91.756
1          144.875000  2006-01-02  ...   0.0 2006-01-02    33.636    -91.756
2          147.666667  2006-01-03  ...   0.0 2006-01-03    33.636    -91.756
3          116.416667  2006-01-04  ...   0.0 2006-01-04    33.636    -91.756
4          142.666667  2006-01-05  ...   0.0 2006-01-05    33.636    -91.756
...               ...         ...  ...   ...        ...       ...        ...
732349  999999.900000  2024-11-26  ...   0.0 2024-11-26    36.118    -97.091
732350  999999.900000  2024-11-27  ...   0.0 2024-11-27    36.118    -97.091
732351  999999.900000  2024-11-28  ...   0.0 2024-11-28    36.118    -97.091
732352  999999.900000  2024-11-29  ...   0.0 2024-11-29    36.118    -97.091
732353  999999.900000  2024-11-30  ...   0.0 2024-11-30    36.118    -97.091

       elevation  region  Year  Month  Day  solar_activity
0           85.0       4  2006      1    1              34
1           85.0       4  2006      1    2              33
2           85.0       4  2006      1    3              26
3           85.0       4  2006      1    4              23
4           85.0       4  2006      1    5              20
...          ...     ...   ...    ...  ...             ...
732349     271.3       4  2024     11   26             160
732350     271.3       4  2024     11   27             205
732351     271.3       4  2024     11   28             170
732352     271.3       4  2024     11   29             161
732353     271.3       4  2024     11   30             121

[732354 rows x 23 columns]

In [72]:
#Confirm there are no NaN values for solar activity
combined_df[combined_df['date'] < datetime.strptime("2025-1-1", "%Y-%m-%d")].isna().sum()

time                       0
temperatures              65
slp                       65
vapor_pressure            65
wet_bulb_temperature      65
specific_humidity         65
file_id                    0
water                      0
GHI                        0
DATE                       0
STATION                 1644
WDSP                    8545
PRCP                    2158
SNDP                    1644
date                       0
latitude                   0
longitude                  0
elevation                  0
region                     0
Year                       0
Month                      0
Day                        0
solar_activity             0
dtype: int64

In [76]:
# Count negative (missing) values
count = (combined_df['solar_activity'] < 0).sum()
print(count)

0

In [82]:
# Set the date column as the index
combined_df.set_index('date', inplace=True)

#Drop STATION (not needed)
combined_df = combined_df.drop(['STATION'], axis=1)

# Perform linear interpolation to fill NaN values
combined_df['temperatures'] = combined_df['temperatures'].interpolate(method='linear')
combined_df['slp'] = combined_df['slp'].interpolate(method='linear')
combined_df['vapor_pressure'] = combined_df['vapor_pressure'].interpolate(method='linear')
combined_df['wet_bulb_temperature'] = combined_df['wet_bulb_temperature'].interpolate(method='linear')
combined_df['specific_humidity'] = combined_df['specific_humidity'].interpolate(method='linear')
combined_df['WDSP'] = combined_df['WDSP'].interpolate(method='linear')
combined_df['PRCP'] = combined_df['PRCP'].interpolate(method='linear')
combined_df['SNDP'] = combined_df['SNDP'].interpolate(method='linear')

In [83]:
# Reset the index to get back the date column
combined_df.reset_index(inplace=True)

#Confirm there are no NaN values left and data is clean
combined_df[combined_df['date'] < datetime.strptime("2025-1-1", "%Y-%m-%d")].isna().sum()

date                    0
time                    0
temperatures            0
slp                     0
vapor_pressure          0
wet_bulb_temperature    0
specific_humidity       0
file_id                 0
water                   0
GHI                     0
DATE                    0
WDSP                    0
PRCP                    0
SNDP                    0
latitude                0
longitude               0
elevation               0
region                  0
Year                    0
Month                   0
Day                     0
solar_activity          0
dtype: int64

In [84]:
#Write full daily binned dataset to CSV file
combined_df.to_csv('Final_Daily_Dataset.csv')

In [116]:
#Function to bin data to monthly
def resample(group):
    return group.resample('ME').mean()

# Set 'date' as the index
combined_df.set_index('date', inplace=True)

# Drop DATE and time columns which can cause problems with binning
combined_df = combined_df.drop(['DATE', 'time'], axis=1)

#Bin the data to monthly
monthly_data = combined_df.groupby('file_id').apply(resample, include_groups=False)

print(monthly_data)

                    temperatures          slp  vapor_pressure  \
file_id date
6501    2006-01-31     12.209677  1018.534543        8.674922
        2006-02-28      8.174541  1021.230347        6.942276
        2006-03-31     15.676613  1018.968548       10.468176
        2006-04-30     22.464167  1014.686944       16.358802
        2006-05-31     23.657258  1014.236828       18.798749
...                          ...          ...             ...
9858    2024-07-31     28.604704  1013.969355       23.769169
        2024-08-31     29.114919  1015.112097       23.699154
        2024-09-30     24.570278  1014.393750       16.790240
        2024-10-31     21.159140  1018.230376       10.994776
        2024-11-30     12.112917  1015.400069        9.888937

                    wet_bulb_temperature  specific_humidity  water  \
file_id date
6501    2006-01-31              7.759507           5.386935    1.0
        2006-02-28              4.326557           4.299929    1.0
        2006-03-31             10.491486           6.505135    1.0
        2006-04-30             16.981874          10.211263    1.0
        2006-05-31             18.675700          11.737971    1.0
...                                  ...                ...    ...
9858    2024-07-31             22.781443          15.211417    1.0
        2024-08-31             22.875429          15.149811    1.0
        2024-09-30             18.061455          10.720199    1.0
        2024-10-31             13.388460           6.989922    1.0
        2024-11-30              8.511346           6.313758    1.0

                              GHI      WDSP      PRCP  SNDP  latitude  \
file_id date
6501    2006-01-31     108.340054  6.348387  0.234516   0.0    33.636
        2006-02-28     126.000000  4.871429  0.166429   0.0    33.636
        2006-03-31     180.936828  6.396774  0.170645   0.0    33.636
        2006-04-30     241.309722  5.590000  0.108000   0.0    33.636
        2006-05-31     260.038978  4.967742  0.113226   0.0    33.636
...                           ...       ...       ...   ...       ...
9858    2024-07-31  999999.900000  7.200000  0.080323   0.0    36.118
        2024-08-31  999999.900000  7.200000  0.115161   0.0    36.118
        2024-09-30  999999.900000  7.200000  0.013667   0.0    36.118
        2024-10-31  999999.900000  7.200000  0.035806   0.0    36.118
        2024-11-30  999999.900000  7.200000  0.283667   0.0    36.118

                    longitude  elevation  region    Year  Month   Day  \
file_id date
6501    2006-01-31    -91.756       85.0     4.0  2006.0    1.0  16.0
        2006-02-28    -91.756       85.0     4.0  2006.0    2.0  14.5
        2006-03-31    -91.756       85.0     4.0  2006.0    3.0  16.0
        2006-04-30    -91.756       85.0     4.0  2006.0    4.0  15.5
        2006-05-31    -91.756       85.0     4.0  2006.0    5.0  16.0
...                       ...        ...     ...     ...    ...   ...
9858    2024-07-31    -97.091      271.3     4.0  2024.0    7.0  16.0
        2024-08-31    -97.091      271.3     4.0  2024.0    8.0  16.0
        2024-09-30    -97.091      271.3     4.0  2024.0    9.0  15.5
        2024-10-31    -97.091      271.3     4.0  2024.0   10.0  16.0
        2024-11-30    -97.091      271.3     4.0  2024.0   11.0  15.5

                    solar_activity
file_id date
6501    2006-01-31       20.903226
        2006-02-28        5.714286
        2006-03-31       17.290323
        2006-04-30       50.266667
        2006-05-31       37.225806
...                            ...
9858    2024-07-31      196.548387
        2024-08-31      215.516129
        2024-09-30      141.366667
        2024-10-31      166.387097
        2024-11-30      152.466667

[24062 rows x 18 columns]

In [117]:
# Reset the index to get back the date column
monthly_data.reset_index(inplace=True)

print(monthly_data)

       file_id       date  temperatures          slp  vapor_pressure  \
0         6501 2006-01-31     12.209677  1018.534543        8.674922
1         6501 2006-02-28      8.174541  1021.230347        6.942276
2         6501 2006-03-31     15.676613  1018.968548       10.468176
3         6501 2006-04-30     22.464167  1014.686944       16.358802
4         6501 2006-05-31     23.657258  1014.236828       18.798749
...        ...        ...           ...          ...             ...
24057     9858 2024-07-31     28.604704  1013.969355       23.769169
24058     9858 2024-08-31     29.114919  1015.112097       23.699154
24059     9858 2024-09-30     24.570278  1014.393750       16.790240
24060     9858 2024-10-31     21.159140  1018.230376       10.994776
24061     9858 2024-11-30     12.112917  1015.400069        9.888937

       wet_bulb_temperature  specific_humidity  water            GHI  \
0                  7.759507           5.386935    1.0     108.340054
1                  4.326557           4.299929    1.0     126.000000
2                 10.491486           6.505135    1.0     180.936828
3                 16.981874          10.211263    1.0     241.309722
4                 18.675700          11.737971    1.0     260.038978
...                     ...                ...    ...            ...
24057             22.781443          15.211417    1.0  999999.900000
24058             22.875429          15.149811    1.0  999999.900000
24059             18.061455          10.720199    1.0  999999.900000
24060             13.388460           6.989922    1.0  999999.900000
24061              8.511346           6.313758    1.0  999999.900000

           WDSP      PRCP  SNDP  latitude  longitude  elevation  region  \
0      6.348387  0.234516   0.0    33.636    -91.756       85.0     4.0
1      4.871429  0.166429   0.0    33.636    -91.756       85.0     4.0
2      6.396774  0.170645   0.0    33.636    -91.756       85.0     4.0
3      5.590000  0.108000   0.0    33.636    -91.756       85.0     4.0
4      4.967742  0.113226   0.0    33.636    -91.756       85.0     4.0
...         ...       ...   ...       ...        ...        ...     ...
24057  7.200000  0.080323   0.0    36.118    -97.091      271.3     4.0
24058  7.200000  0.115161   0.0    36.118    -97.091      271.3     4.0
24059  7.200000  0.013667   0.0    36.118    -97.091      271.3     4.0
24060  7.200000  0.035806   0.0    36.118    -97.091      271.3     4.0
24061  7.200000  0.283667   0.0    36.118    -97.091      271.3     4.0

         Year  Month   Day  solar_activity
0      2006.0    1.0  16.0       20.903226
1      2006.0    2.0  14.5        5.714286
2      2006.0    3.0  16.0       17.290323
3      2006.0    4.0  15.5       50.266667
4      2006.0    5.0  16.0       37.225806
...       ...    ...   ...             ...
24057  2024.0    7.0  16.0      196.548387
24058  2024.0    8.0  16.0      215.516129
24059  2024.0    9.0  15.5      141.366667
24060  2024.0   10.0  16.0      166.387097
24061  2024.0   11.0  15.5      152.466667

[24062 rows x 20 columns]

In [118]:
# Replace back the numeric 999999.9 values with NaN values in GHI 
monthly_data['GHI'] = monthly_data['GHI'].replace({999999.9: np.nan})

print(monthly_data)

       file_id       date  temperatures          slp  vapor_pressure  \
0         6501 2006-01-31     12.209677  1018.534543        8.674922
1         6501 2006-02-28      8.174541  1021.230347        6.942276
2         6501 2006-03-31     15.676613  1018.968548       10.468176
3         6501 2006-04-30     22.464167  1014.686944       16.358802
4         6501 2006-05-31     23.657258  1014.236828       18.798749
...        ...        ...           ...          ...             ...
24057     9858 2024-07-31     28.604704  1013.969355       23.769169
24058     9858 2024-08-31     29.114919  1015.112097       23.699154
24059     9858 2024-09-30     24.570278  1014.393750       16.790240
24060     9858 2024-10-31     21.159140  1018.230376       10.994776
24061     9858 2024-11-30     12.112917  1015.400069        9.888937

       wet_bulb_temperature  specific_humidity  water         GHI      WDSP  \
0                  7.759507           5.386935    1.0  108.340054  6.348387
1                  4.326557           4.299929    1.0  126.000000  4.871429
2                 10.491486           6.505135    1.0  180.936828  6.396774
3                 16.981874          10.211263    1.0  241.309722  5.590000
4                 18.675700          11.737971    1.0  260.038978  4.967742
...                     ...                ...    ...         ...       ...
24057             22.781443          15.211417    1.0         NaN  7.200000
24058             22.875429          15.149811    1.0         NaN  7.200000
24059             18.061455          10.720199    1.0         NaN  7.200000
24060             13.388460           6.989922    1.0         NaN  7.200000
24061              8.511346           6.313758    1.0         NaN  7.200000

           PRCP  SNDP  latitude  longitude  elevation  region    Year  Month  \
0      0.234516   0.0    33.636    -91.756       85.0     4.0  2006.0    1.0
1      0.166429   0.0    33.636    -91.756       85.0     4.0  2006.0    2.0
2      0.170645   0.0    33.636    -91.756       85.0     4.0  2006.0    3.0
3      0.108000   0.0    33.636    -91.756       85.0     4.0  2006.0    4.0
4      0.113226   0.0    33.636    -91.756       85.0     4.0  2006.0    5.0
...         ...   ...       ...        ...        ...     ...     ...    ...
24057  0.080323   0.0    36.118    -97.091      271.3     4.0  2024.0    7.0
24058  0.115161   0.0    36.118    -97.091      271.3     4.0  2024.0    8.0
24059  0.013667   0.0    36.118    -97.091      271.3     4.0  2024.0    9.0
24060  0.035806   0.0    36.118    -97.091      271.3     4.0  2024.0   10.0
24061  0.283667   0.0    36.118    -97.091      271.3     4.0  2024.0   11.0

        Day  solar_activity
0      16.0       20.903226
1      14.5        5.714286
2      16.0       17.290323
3      15.5       50.266667
4      16.0       37.225806
...     ...             ...
24057  16.0      196.548387
24058  16.0      215.516129
24059  15.5      141.366667
24060  16.0      166.387097
24061  15.5      152.466667

[24062 rows x 20 columns]

In [133]:
# Define the directory containing the files 
path_ONI = current_directory+"\\Data\\ONI\\"

print(path_ONI)

filename_ONI = path_ONI + 'ONIData.txt'

# Read ONI data into a dataframe
ONI_df = pd.read_csv(filename_ONI, delimiter=r'\s+')

print(ONI_df)

C:\Users\User\Data\ONI\
       YR  MON  TOTAL  ClimAdjust  ANOM
0    1950    1  24.56       26.18 -1.62
1    1950    2  25.07       26.39 -1.32
2    1950    3  25.88       26.95 -1.07
3    1950    4  26.29       27.39 -1.11
4    1950    5  26.19       27.56 -1.37
..    ...  ...    ...         ...   ...
894  2024    7  27.34       27.29  0.05
895  2024    8  26.74       26.86 -0.11
896  2024    9  26.46       26.72 -0.25
897  2024   10  26.45       26.72 -0.26
898  2024   11  26.51       26.70 -0.19

[899 rows x 5 columns]

In [134]:
import calendar

#Function to get end of the month date for ONI dataset
def get_end_of_month(year, month):
    # Get the last day of the month
    last_day = calendar.monthrange(year, month)[1]
    # Return the date as a string in the format YYYY-MM-DD
    return f"{year}-{month:02d}-{last_day:02d}"

#create new date column to fill
ONI_df['date'] = '2020-1-1'

# Set date column to be last day of the month
for i in range(ONI_df.shape[0]):
    ONI_df.loc[i, 'date'] = get_end_of_month(ONI_df['YR'].values[i], ONI_df['MON'].values[i])

print(ONI_df)

       YR  MON  TOTAL  ClimAdjust  ANOM        date
0    1950    1  24.56       26.18 -1.62  1950-01-31
1    1950    2  25.07       26.39 -1.32  1950-02-28
2    1950    3  25.88       26.95 -1.07  1950-03-31
3    1950    4  26.29       27.39 -1.11  1950-04-30
4    1950    5  26.19       27.56 -1.37  1950-05-31
..    ...  ...    ...         ...   ...         ...
894  2024    7  27.34       27.29  0.05  2024-07-31
895  2024    8  26.74       26.86 -0.11  2024-08-31
896  2024    9  26.46       26.72 -0.25  2024-09-30
897  2024   10  26.45       26.72 -0.26  2024-10-31
898  2024   11  26.51       26.70 -0.19  2024-11-30

[899 rows x 6 columns]

In [135]:
#Drop all columns not needed for our final dataset
ONI_df = ONI_df.iloc[:, -2:]

print(ONI_df)

     ANOM        date
0   -1.62  1950-01-31
1   -1.32  1950-02-28
2   -1.07  1950-03-31
3   -1.11  1950-04-30
4   -1.37  1950-05-31
..    ...         ...
894  0.05  2024-07-31
895 -0.11  2024-08-31
896 -0.25  2024-09-30
897 -0.26  2024-10-31
898 -0.19  2024-11-30

[899 rows x 2 columns]

In [136]:
ONI_df.columns = ['ONI', 'date']

print(ONI_df)

      ONI        date
0   -1.62  1950-01-31
1   -1.32  1950-02-28
2   -1.07  1950-03-31
3   -1.11  1950-04-30
4   -1.37  1950-05-31
..    ...         ...
894  0.05  2024-07-31
895 -0.11  2024-08-31
896 -0.25  2024-09-30
897 -0.26  2024-10-31
898 -0.19  2024-11-30

[899 rows x 2 columns]

In [139]:
monthly_data.reset_index(inplace=True)
ONI_df.reset_index(inplace=True)

ONI_df['date'] = pd.to_datetime(ONI_df['date'])

monthly_data.set_index('date', inplace=True)
ONI_df.set_index('date', inplace=True)

In [140]:
final_monthly_dataset_df = pd.merge(monthly_data, ONI_df, on='date', how='left')

print(final_monthly_dataset_df)

            level_0  index_x  file_id  temperatures          slp  \
date
2006-01-31        0        0     6501     12.209677  1018.534543
2006-02-28        1        1     6501      8.174541  1021.230347
2006-03-31        2        2     6501     15.676613  1018.968548
2006-04-30        3        3     6501     22.464167  1014.686944
2006-05-31        4        4     6501     23.657258  1014.236828
...             ...      ...      ...           ...          ...
2024-07-31    24057    24057     9858     28.604704  1013.969355
2024-08-31    24058    24058     9858     29.114919  1015.112097
2024-09-30    24059    24059     9858     24.570278  1014.393750
2024-10-31    24060    24060     9858     21.159140  1018.230376
2024-11-30    24061    24061     9858     12.112917  1015.400069

            vapor_pressure  wet_bulb_temperature  specific_humidity  water  \
date
2006-01-31        8.674922              7.759507           5.386935    1.0
2006-02-28        6.942276              4.326557           4.299929    1.0
2006-03-31       10.468176             10.491486           6.505135    1.0
2006-04-30       16.358802             16.981874          10.211263    1.0
2006-05-31       18.798749             18.675700          11.737971    1.0
...                    ...                   ...                ...    ...
2024-07-31       23.769169             22.781443          15.211417    1.0
2024-08-31       23.699154             22.875429          15.149811    1.0
2024-09-30       16.790240             18.061455          10.720199    1.0
2024-10-31       10.994776             13.388460           6.989922    1.0
2024-11-30        9.888937              8.511346           6.313758    1.0

                   GHI  ...  latitude  longitude  elevation  region    Year  \
date                    ...
2006-01-31  108.340054  ...    33.636    -91.756       85.0     4.0  2006.0
2006-02-28  126.000000  ...    33.636    -91.756       85.0     4.0  2006.0
2006-03-31  180.936828  ...    33.636    -91.756       85.0     4.0  2006.0
2006-04-30  241.309722  ...    33.636    -91.756       85.0     4.0  2006.0
2006-05-31  260.038978  ...    33.636    -91.756       85.0     4.0  2006.0
...                ...  ...       ...        ...        ...     ...     ...
2024-07-31         NaN  ...    36.118    -97.091      271.3     4.0  2024.0
2024-08-31         NaN  ...    36.118    -97.091      271.3     4.0  2024.0
2024-09-30         NaN  ...    36.118    -97.091      271.3     4.0  2024.0
2024-10-31         NaN  ...    36.118    -97.091      271.3     4.0  2024.0
2024-11-30         NaN  ...    36.118    -97.091      271.3     4.0  2024.0

            Month   Day  solar_activity  index_y   ONI
date
2006-01-31    1.0  16.0       20.903226      672 -0.91
2006-02-28    2.0  14.5        5.714286      673 -0.67
2006-03-31    3.0  16.0       17.290323      674 -0.71
2006-04-30    4.0  15.5       50.266667      675 -0.32
2006-05-31    5.0  16.0       37.225806      676 -0.09
...           ...   ...             ...      ...   ...
2024-07-31    7.0  16.0      196.548387      894  0.05
2024-08-31    8.0  16.0      215.516129      895 -0.11
2024-09-30    9.0  15.5      141.366667      896 -0.25
2024-10-31   10.0  16.0      166.387097      897 -0.26
2024-11-30   11.0  15.5      152.466667      898 -0.19

[24062 rows x 23 columns]

In [141]:
final_monthly_dataset_df.reset_index(inplace=True)

final_monthly_dataset_df = final_monthly_dataset_df.drop(['index_x', 'index_y', 'level_0'], axis=1)

print(final_monthly_dataset_df)

            date  file_id  temperatures          slp  vapor_pressure  \
0     2006-01-31     6501     12.209677  1018.534543        8.674922
1     2006-02-28     6501      8.174541  1021.230347        6.942276
2     2006-03-31     6501     15.676613  1018.968548       10.468176
3     2006-04-30     6501     22.464167  1014.686944       16.358802
4     2006-05-31     6501     23.657258  1014.236828       18.798749
...          ...      ...           ...          ...             ...
24057 2024-07-31     9858     28.604704  1013.969355       23.769169
24058 2024-08-31     9858     29.114919  1015.112097       23.699154
24059 2024-09-30     9858     24.570278  1014.393750       16.790240
24060 2024-10-31     9858     21.159140  1018.230376       10.994776
24061 2024-11-30     9858     12.112917  1015.400069        9.888937

       wet_bulb_temperature  specific_humidity  water         GHI      WDSP  \
0                  7.759507           5.386935    1.0  108.340054  6.348387
1                  4.326557           4.299929    1.0  126.000000  4.871429
2                 10.491486           6.505135    1.0  180.936828  6.396774
3                 16.981874          10.211263    1.0  241.309722  5.590000
4                 18.675700          11.737971    1.0  260.038978  4.967742
...                     ...                ...    ...         ...       ...
24057             22.781443          15.211417    1.0         NaN  7.200000
24058             22.875429          15.149811    1.0         NaN  7.200000
24059             18.061455          10.720199    1.0         NaN  7.200000
24060             13.388460           6.989922    1.0         NaN  7.200000
24061              8.511346           6.313758    1.0         NaN  7.200000

       ...  SNDP  latitude  longitude  elevation  region    Year  Month   Day  \
0      ...   0.0    33.636    -91.756       85.0     4.0  2006.0    1.0  16.0
1      ...   0.0    33.636    -91.756       85.0     4.0  2006.0    2.0  14.5
2      ...   0.0    33.636    -91.756       85.0     4.0  2006.0    3.0  16.0
3      ...   0.0    33.636    -91.756       85.0     4.0  2006.0    4.0  15.5
4      ...   0.0    33.636    -91.756       85.0     4.0  2006.0    5.0  16.0
...    ...   ...       ...        ...        ...     ...     ...    ...   ...
24057  ...   0.0    36.118    -97.091      271.3     4.0  2024.0    7.0  16.0
24058  ...   0.0    36.118    -97.091      271.3     4.0  2024.0    8.0  16.0
24059  ...   0.0    36.118    -97.091      271.3     4.0  2024.0    9.0  15.5
24060  ...   0.0    36.118    -97.091      271.3     4.0  2024.0   10.0  16.0
24061  ...   0.0    36.118    -97.091      271.3     4.0  2024.0   11.0  15.5

       solar_activity   ONI
0           20.903226 -0.91
1            5.714286 -0.67
2           17.290323 -0.71
3           50.266667 -0.32
4           37.225806 -0.09
...               ...   ...
24057      196.548387  0.05
24058      215.516129 -0.11
24059      141.366667 -0.25
24060      166.387097 -0.26
24061      152.466667 -0.19

[24062 rows x 21 columns]

In [145]:
#Confirm there are no NaN values left (except GHI) and data is clean
final_monthly_dataset_df[final_monthly_dataset_df['date'] < datetime.strptime("2025-1-1", "%Y-%m-%d")].isna().sum()

date                       0
file_id                    0
temperatures               0
slp                        0
vapor_pressure             0
wet_bulb_temperature       0
specific_humidity          0
water                      0
GHI                     4982
WDSP                       0
PRCP                       0
SNDP                       0
latitude                   0
longitude                  0
elevation                  0
region                     0
Year                       0
Month                      0
Day                        0
solar_activity             0
ONI                        0
dtype: int64

In [147]:
# Count ONI values below -3
count = (final_monthly_dataset_df['ONI'] < -3).sum()
print(count)
# Count ONI values above 3
count = (final_monthly_dataset_df['ONI'] > 3).sum()
print(count)
# Count ONI values less than 3
count = (final_monthly_dataset_df['ONI'] < 3).sum()
print(count)

0
0
24062

In [142]:
#Write full monthly binned dataset to CSV file
final_monthly_dataset_df.to_csv('Final_Monthly_Dataset.csv')